#!/bin/bash

echo "==================================="
echo "VendorHub Deployment Helper"
echo "==================================="
echo ""

# Check if running from correct directory
if [ ! -d "marketplace-frontend" ] || [ ! -d "marketplace-backend" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

echo "📋 Deployment Checklist:"
echo ""
echo "1. ✅ Created deployment configuration files"
echo "2. ✅ Backend: railway.yaml, render.yaml, Procfile"
echo "3. ✅ Frontend: vercel.json"
echo ""

echo "🚀 Quick Deployment Steps:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 1: Fastest Deployment (Using CLIs)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 Frontend (Vercel):"
echo "   cd marketplace-frontend"
echo "   npm install -g vercel"
echo "   vercel login"
echo "   vercel --prod"
echo ""
echo "🔧 Backend (Railway):"
echo "   npm install -g @railway/cli"
echo "   railway login"
echo "   cd marketplace-backend"
echo "   railway init"
echo "   railway up"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 2: No CLI Required (Using Web)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 Frontend:"
echo "   1. Go to: https://vercel.com"
echo "   2. Click 'Import Project'"
echo "   3. Connect your GitHub repository"
echo "   4. Vercel auto-deploys Next.js!"
echo ""
echo "🔧 Backend:"
echo "   1. Go to: https://railway.app"
echo "   2. Click 'New Project' → 'Deploy from GitHub'"
echo "   3. Select your repository"
echo "   4. Railway auto-deploys Spring Boot!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 After Deployment:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Get your backend URL from Railway"
echo "2. Update Vercel environment variable:"
echo "   NEXT_PUBLIC_API_URL = <your-backend-url>"
echo "3. Redeploy frontend on Vercel"
echo "4. Your demo is live! 🎉"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💾 Database (MongoDB Atlas):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://www.mongodb.com/cloud/atlas"
echo "2. Create free M0 cluster (512MB free)"
echo "3. Get connection string"
echo "4. Add to Railway environment variables"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚡ Estimated Time:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Frontend: 2-3 minutes"
echo "  Backend: 5-7 minutes"
echo "  Total: ~10 minutes!"
echo ""

echo "📖 For detailed instructions, see: DEPLOYMENT_GUIDE.md"
echo ""
echo "🎯 Need help? Just ask!"
echo ""
